image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production
  
variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: 'nitrate/reddit'

.registry_common:
  stage: build
  before_script:
    - echo 'Login to Docker Hub'
    - docker login -u nitrate -p ${DOCKER_HUB_PWD}
    - docker info
  after_script:
    - docker logout

.build_before:
  before_script:
    - echo 'Bundle install reddit app'
    - cd reddit
    - bundle install

build_app_job:
  extends: .build_before
  stage: build
  script:
    - echo 'Building'

build_image_job:
  extends: .registry_common
  stage: build
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker build  -t ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME} -t ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA} ./reddit/.
    - docker push ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}

test_unit_job:
  extends: .build_before
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  extends: .registry_common
  stage: review
  image: docker:19.03.12
  services:
    - docker:dind
  script: 
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker stop $(docker ps -q -a --filter "name=review.${CI_ENVIRONMENT_SLUG}") || true
    - docker run
      -d
      -p 9292:9292
      --name review.${CI_ENVIRONMENT_SLUG}
      --rm
      ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
