version: '3.3'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    image: ${USER_NAME}/ui:${TAG_VER}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:${TAG_VER}
    environment:
      - POST_DATABASE_HOST=mongo
    networks:
      - front_net
      - back_net

  comment:
    image: ${USER_NAME}/comment:${TAG_VER}
    environment:
      - COMMENT_DATABASE_HOST=mongo
    networks:
      - front_net
      - back_net

  prometheus:
    image: $USER_NAME/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - front_net
      - back_net
    command: # Передаем доппараметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - front_net
      - back_net
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  
volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
#    name: back_net
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
#    name: front_net
    ipam:
      config:
        - subnet: 10.0.1.0/24
