---
- name: Install docker ce & docker-compose
  hosts: all
  become: yes
  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg2
          - python3-pip
        state: present
        update_cache: yes
    
    - name: Add an apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Install docker
      apt: update_cache=yes name=docker-ce state=present
    
    - name: Add user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Docker Module for Python
      pip:
        name: 
          - docker
          - docker-compose

    - name: reset the ssh connection
      meta: reset_connection
